LLAMA_3_3_70B_UUID = "d754f2d7-d1f0-11ef-bf8f-4e013e2ddde4"
AUDITOR_AGENT_NAME = "Auditor Agent"
CRITIC_AGENT_NAME = "Auditor Critic Sub-Agent"
REVISOR_AGENT_NAME = "Auditor Revisor Sub-Agent"
DEFAULT_REGION = "tor1"

RUNNING_STATUS = "STATUS_RUNNING"
POLL_FREQUENCY = 60
MAX_WAIT_TIME = 60 * 15
